name = "live"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "quiz.int.vidio.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "stkipnurulhuda.ac.id.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "quiz.vidio.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "bakrie.ac.id.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "quiz.vidio.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "quiz.int.vidio.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "graph.instagram.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "investors.spotify.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "cache.netflix.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "creativeservices.netflix.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "zaintest.vuclip.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "live.iflix.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "io.ruangguru.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "gw.ruangguru.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "www.udemy.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "udemy.com.live.wifiku.site"
custom_domain = true

[[routes]]
pattern = "beta.zoom.us.live.wifiku.site"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
