name = "wife"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "146.190.88.245"
UUID = "577db0f3-4cbc-4f29-85e4-77037b9ae49b"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
